### ISSUE TITLE
Ambiguous call

### ISSUE THREAD

**Issue by tavoarcila** [gigi81/sharpfastcgi#8]
Hi Luigi,

I've been using an old version (2011) of your fantastic library in a program I have, but mysteriously about a month ago the program began to slow in responding and randomly generate some connection timeouts. After discarding memory and physical connection problems, I tried to upgrade to the latest version, but when I compile I get an error, even when trying to compile the examples downloaded from GitHub.

I'm running Ubuntu 15.04 and mono 5.5

Error I'm getting is:  
/home/gustavo/Downloads/sharpfastcgi-master/FastCgi/ImmutableArray/ImmutableArray.cs(23,23): Error CS0121: The call is ambiguous between the following methods or properties: `FastCgi.ImmutableArray.ImmutableArray<T>.operator !=(FastCgi.ImmutableArray.ImmutableArray<T>, FastCgi.ImmutableArray.ImmutableArray<T>)' and `FastCgi.ImmutableArray.ImmutableArray<T>.operator !=(FastCgi.ImmutableArray.ImmutableArray<T>, T[])' (CS0121) (FastCgi)

at line 300 of ImmutableArray.cs

I'm a php developer,  not a c# developer but I can do some basic things and did integrate your fastcgi library by following the samples, but honestly now I can't understand why this, Ive tried to understand by reading your article abour Inmmutable Arrays, http://www.codeproject.com/Articles/140138/Immutable-Array-for-NET, but honestly I feel dummy.

Can you please guide me in the right direction and help me solve this please?

Cheers,

Gustavo Arcila

**Comment by gigi81** [comment]
Hi Gustavo,
I added some refactoring a few months ago to the api that I was holding back when I had more time to work on it... anyway I committed that stuff today and tried to build on my mac. I found the same problem you had (windows build is fine for the record) and I think I fixed the build error in 1e726eb6f39e625bc61af48fd9648da0e919c3c8 It is just skipping some code that is not used anyway but it seems to get mono compiler a little confused. Let me know how it goes.

**Comment by tavoarcila** [comment]
Hi Luigi,

Thank you for your quick response. I'll check and let you know,

Gustavo

**Comment by gigi81** [comment]
@tavoarcila can we close this?

**Comment by tavoarcila** [comment]
Yes sure, (sorry didn't knew I have to close the issue, I'm really a dummy at Git), Thank you so much for your quick and kind help

**Comment by gigi81** [comment]
no problem!
